// Generated by https://quicktype.io

export interface PerfilInstructor {
  id: number;
  biografia: string;
  calificacion: number;
  usuarioId: number;
  cursos: Curso[];
  usuario: Usuario;
}

export interface Curso {
  id: number;
  nombre: string;
  fecha_creacion: string;
  precio: number;
  descripcion: string;
  foto: string;
  descuento: null;
  estado: number;
  instructorId: number;
}

export interface Usuario {
  id: number;
  nombre: string;
  apellido: string;
  email: string;
  clave: string;
  telefono: number;
  pais: string;
  fotografia: null;
}
