// Generated by https://quicktype.io

export interface Cursos {
  id: number;
  nombre: string;
  fecha_creacion: string;
  precio: number;
  descripcion: string;
  foto: string;
  descuento: null;
  estado: number;
  instructorId: number;
  videos: Video[];
  instructor: Instructor;
}

export interface Instructor {
  id: number;
  biografia: string;
  calificacion: number;
  usuarioId: number;
  usuario: Usuario;
}

export interface Usuario {
  id: number;
  nombre: string;
  apellido: string;
  email: string;
  clave: string;
  telefono: number;
  pais: string;
  fotografia: string;
}

export interface Video {
  id: number;
  titulo: string;
  descripcion: string;
  estado: number;
  video: string;
  cursoId: number;
}
