// Generated by https://quicktype.io

export interface CursoCategoria {
  id: number;
  nombre: string;
  fecha_creacion: string;
  precio: number;
  descripcion: string;
  foto: string;
  descuento: null;
  estado: number;
  instructorId: number;
  categoria: Categoria[];
  instructor: Instructor;
}

export interface Categoria {
  id: number;
  nombre: string;
  descripcion: string;
  categoria_curso: CategoriaCurso;
}

export interface CategoriaCurso {
  id: number;
}

export interface Instructor {
  id: number;
  biografia: string;
  calificacion: number;
  usuarioId: number;
  usuario: Usuario;
}

export interface Usuario {
  id: number;
  nombre: string;
  apellido: string;
  email: string;
  clave: string;
  telefono: number;
  pais: string;
  fotografia: null;
}
