// Generated by https://quicktype.io

export interface Curso {
  id: number;
  nombre: string;
  fecha_creacion: string;
  precio: number;
  descripcion: string;
  foto: string;
  descuento: null;
  estado: number;
  instructor: Instructor;
}

interface Instructor {
  id: number;
  biografia: string;
  calificacion: number;
  usuarioId: number;
  usuario: Usuario;
}

export interface Usuario {
  id: number;
  nombre: string;
  apellido: string;
  email: string;
  telefono: number;
  pais: string;
  fotografia: string;
}

export interface PostCurso {
  portada: string;
  nombre: string;
  precio: number;
  descripcion: string;
  instructorId: number;
}
